export const characters = [
    { id: 1, name: "Naruto Uzumaki", series: "Naruto", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/4ce09afc0abbd47cbe6d1514e08d4c3b.jpg" },
    { id: 2, name: "Sasuke Uchiha", series: "Naruto", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/HD-wallpaper-sasuke-uchiha-sasuke-uchiha-naruto-anime.jpg" },
    { id: 3, name: "Monkey D. Luffy", series: "One Piece", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/7ad492e5d36eb39370285e659f659433.jpg" },
    { id: 4, name: "Roronoa Zoro", series: "One Piece", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/Zoro.webp" },
    { id: 5, name: "Satoru Gojo", series: "Jujutsu Kaisen", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/thumb-1920-1332281.jpeg" },
    { id: 6, name: "Yuji Itadori", series: "Jujutsu Kaisen", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/a9afdafb6c6900721df61b32700f788b.jpg" },
    { id: 7, name: "Tanjiro Kamado", series: "Demon Slayer", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/m_2Fx1000_2F64ceae43-27b5-4845-8e77-d6a06980b68b_d62075bc-e2d6-4a69-ab28-fce7d02479a9.jpg" },
    { id: 8, name: "Nezuko Kamado", series: "Demon Slayer", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/__kamado_nezuko_kimetsu_no_yaiba_drawn_by_dodon_gadon__sample-a51d2c1bda1ed877dbde6f8e50dbb2e2.jpg" },
    { id: 9, name: "Izuku Midoriya", series: "My Hero Academia", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/do-you-think-deku-has-better-writing-than-what-most-people-v0-qpyo5m09ejke1.jpeg" },
    { id: 10, name: "Katsuki Bakugo", series: "My Hero Academia", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/d1255e03e0efb1f84f1fe90b3751106a.jpg" },
    { id: 11, name: "Goku", series: "Dragon Ball Z", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/qm1Tw.jpg" },
    { id: 12, name: "Vegeta", series: "Dragon Ball Z", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/super-saiyan-blue-vegeta-dragon-ball-super-3044.jpg" },
    { id: 13, name: "Gohan", series: "Dragon Ball Z", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/3e46bf63f966c5bfc2fcf48d4a55b60e.jpg" },
    { id: 14, name: "Picolo", series: "Dragon Ball Z", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/79a33ce9abda6b2583bc00ff780bf491.jpg" },
    { id: 15, name: "Frieza", series: "Dragon Ball Z", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/Go1ARitXUAA1LZT.jpg" },
    { id: 16, name: "Nami", series: "One Piece", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/GaXQS.jpeg" },
    { id: 17, name: "Sanji", series: "One Piece", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/sanji-cool-style-wallpaper-preview.jpg" },
    { id: 18, name: "Nico Robin", series: "One Piece", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/degfyig-4ae28501-55b9-4208-aadb-8dae2c03c4d3.png" },
    { id: 19, name: "Portgas D.Ace", series: "One Piece", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/portgas-d-ace-1080-x-1920-wallpaper-xk3wc0drjxk07y66.jpg" },
    { id: 20, name: "Trafalgar Law", series: "One Piece", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/1991eb19190f376d4b7a8e41b4f88e03.jpg" },
    { id: 21, name: "Kakashi Hatake", series: "Naruto", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/the-6th-hokage-hatake-kakashi-my-version-v0-4m51lgk95guf1.jpeg" },
    { id: 22, name: "Hinata Hyuga", series: "Naruto", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/images%20(15).jpeg" },
    { id: 23, name: "Itachi Uchiha", series: "Naruto", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/HD-wallpaper-itachi-uchiha-top-30-best-itachi-uchiha-itachi-uchiha-manga.jpg" },
    { id: 24, name: "Gaara", series: "Naruto", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/HD-wallpaper-gaara-naruto.jpg" },
    { id: 25, name: "Madara Uchiha", series: "Naruto", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/HD-wallpaper-madara-uchiha-anime-naruto-shippuden-naruto-thumbnail.jpg" },
    { id: 26, name: "Ichigo Kurosaki", series: "Bleach", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/56976182728fc653fc246652ea5d7ff7.jpg" },
    { id: 27, name: "Rukia Kuchiki", series: "Bleach", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/rukia_kuchiki_by_bubbleteexl_dhdgb2y-fullview.jpg" },
    { id: 28, name: "Sosuke Aizen", series: "Bleach", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/%E8%97%8D%E6%9F%93.jpeg" },
    { id: 29, name: "Kenpachi Zaraki", series: "Bleach", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/kenpachi-zaraki-850-x-1512-wallpaper-zrhvxc5e7pjssj4g.jpg" },
    { id: 30, name: "Grimmjow Jaegerjaquez", series: "Bleach", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/HD-wallpaper-anime-bleach-grimmjow-jaegerjaquez.jpg" },
    { id: 31, name: "Gon Freecss", series: "Hunter x Hunter", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/HD-wallpaper-gon-gon-hunter-x-hunter.jpg" },
    { id: 32, name: "Killua Zoldyck", series: "Hunter x Hunter", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/images%20(16).jpeg" },
    { id: 33, name: "Kurapika", series: "Hunter x Hunter", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/ba2452c5f25245c40b8a86a4620ab7cd.jpg" },
    { id: 34, name: "Hisoka Morow", series: "Hunter x Hunter", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/7c1bc0c521a9438d78da4ddabe634c14.jpg" },
    { id: 35, name: "Isaac Netero", series: "Hunter x Hunter", image: "https://raw.githubusercontent.com/UzielHanma/IMGBOTLOADER/main/HD-wallpaper-isaac-netero-anime-hunterxhunter.jpg" },
    { id: 36, name: "Eren Yeager", series: "Attack on Titan", image: "" },
    { id: 37, name: "Mikasa Ackerman", series: "Attack on Titan", image: "" },
    { id: 38, name: "Levi Ackerman", series: "Attack on Titan", image: "" },
    { id: 39, name: "Armin Arlert", series: "Attack on Titan", image: "" },
    { id: 40, name: "Erwin Smith", series: "Attack on Titan", image: "" },
    { id: 41, name: "Edward Elric", series: "Fullmetal Alchemist", image: "" },
    { id: 42, name: "Alphonse Elric", series: "Fullmetal Alchemist", image: "" },
    { id: 43, name: "Roy Mustang", series: "Fullmetal Alchemist", image: "" },
    { id: 44, name: "Riza Hawkeye", series: "Fullmetal Alchemist", image: ""},
    { id: 45, name: "Scar", series: "Fullmetal Alchemist", image: "" },
    { id: 46, name: "Light Yagami", series: "Death Note", image: "" },
    { id: 47, name: "​L Lawliet", series: "Death Note", image: "" },
    { id: 48, name: "Ryuk", series: "Death Note", image: "" },
    { id: 49, name: "Misa Amane", series: "Death Note", image: "" },
    { id: 50, name: "Near", series: "Death Note", image: "" },
    { id: 51, name: "Jotaro Kujo", series: "JoJo's Bizarre Adventure", image: "" },
    { id: 52, name: "Dio Brando", series: "JoJo's Bizarre Adventure", image: "" },
    { id: 53, name: "Joseph Joestar", series: "JoJo's Bizarre Adventure", image: "" },
    { id: 54, name: "Giorno Giovanna", series: "JoJo's Bizarre Adventure", image: "" },
    { id: 55, name: "Jolyne Cujoh", series: "JoJo's Bizarre Adventure", image: "" },
    { id: 56, name: "Shoto Todoroki", series: "My Hero Academia", image: "" },
    { id: 57, name: "All Might", series: "My Hero Academia", image: "" },
    { id: 58, name: "Ochaco Uraraka", series: "My Hero Academia", image: "" },
    { id: 59, name: "Tsuyu Asui", series: "My Hero Academia", image: "" },
    { id: 60, name: "Tomura Shigaraki", series: "My Hero Academia", image: "" },
    { id: 61, name: "Megumi Fushiguro", series: "Jujutsu Kaisen", image: "" },
    { id: 62, name: "Nobara Kugisaki", series: "Jujutsu Kaisen", image: "" },
    { id: 63, name: "Kento Nanami", series: "Jujutsu Kaisen", image: "" },
    { id: 64, name: "Ryomen Sukuna", series: "Jujutsu Kaisen", image: "" },
    { id: 65, name: "Maki Zenin", series: "Jujutsu Kaisen", image: "" },
    { id: 66, name: "Zenitsu Agatsuma", series: "Demon Slayer", image: "" },
    { id: 67, name: "Inosuke Hashibira", series: "Demon Slayer", image: "" },
    { id: 68, name: "Kyojuro Rengoku", series: "Demon Slayer", image: "" },
    { id: 69, name: "Shinobu Kocho", series: "Demon Slayer", image: "" },
    { id: 70, name: "Muzan Kibutsuji", series: "Demon Slayer", image: "" },
    { id: 71, name: "Sung Jin-woo", series: "Solo Leveling", image: "" },
    { id: 72, name: "Cha Hae-in", series: "Solo Leveling", image: "" },
    { id: 73, name: "Igris", series: "Solo Leveling", image: "" },
    { id: 74, name: "Asta", series: "Black Clover", image: "" },
    { id: 75, name: "Yuno", series: "Black Clover", image: "" },
    { id: 76, name: "Noelle Silva", series: "Black Clover", image: "" },
    { id: 77, name: "Yami Sukehiro", series: "Black Clover", image: "" },
    { id: 78, name: "Kirito", series: "Sword Art Online", image: "" },
    { id: 79, name: "Asuna Yuuki", series: "Sword Art Online", image: "" },
    { id: 80, name: "Sinon", series: "Sword Art Online", image: "" },
    { id: 81, name: "Saitama", series: "One Punch Man", image: "" },
    { id: 82, name: "Genos", series: "One Punch Man", image: "" },
    { id: 83, name: "Tstsumaki", series: "One Punch Man", image: "" },
    { id: 84, name: "Garou", series: "One Punch Man", image: "" },
    { id: 85, name: "Ken Kaneki", series: "Tokyo Ghoul", image: "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" },
    { id: 86, name: "Touka Kirishima", series: "Tokyo Ghoul", image: "" },
    { id: 87, name: "Juuzou Suzuya", series: "Tokyo Ghoul", image: "" },
    { id: 88, name: "Saber (Artoria Pendragon)", series: "Fate/stay night", image: "" },
    { id: 89, name: "Archer (Emiya)", series: "Fate/stay night", image: "" },
    { id: 90, name: "Gilgamesh", series: "Fate/stay night", image: "" },
    { id: 91, name: "Lelouch vi Britannia", series: "Code Geass", image: "" },
    { id: 92, name: "​C.C.", series: "Code Geass", image: "" },
    { id: 93, name: "Suzaku Kururugi", series: "Code Geass", image: "" },
    { id: 94, name: "David Martinez", series: "Cyberpunk: Edgerunners", image: "" },
    { id: 95, name: "Lucy", series: "Cyberpunk: Edgerunners", image: "" },
    { id: 96, name: "Rebecca", series: "Cyberpunk: Edgerunners", image: "" },
    { id: 97, name: "Alucard", series: "Hellsing Ultimate", image: "" },
    { id: 98, name: "Seras Victoria", series: "Hellsing Ultimate", image: "" },
    { id: 99, name: "Spike Spiegel", series: "Cowboy Bebop", image: "" },
    { id: 100, name: "Faye Valentine", series: "Cowboy Bebop", image: "" },
];

export const rollGacha = () => {
    // Selección aleatoria simple: todos tienen la misma chance
    const randomIndex = Math.floor(Math.random() * characters.length);
    return characters[randomIndex];
};

